# -*- coding: utf-8 -*-
"""tex 第三轮修补3 — patch_tex_round3c.py
处理 v7 残留叙事 → v9 语境：
A. eq:f_aniso 段（280-284 行）：标注为早期参数化，v9 移除
B. 图10 caption + fig:f_am 正文（762/766-772 行）
C. 收敛节 778 行：等新收敛测试结果后由外层脚本更新（此处不做）
D. 贝叶斯段 780 行 + 可辨识性 782 行
E. 讨论节 793-797 行（Ti64/316L/AlSi 方向依赖描述）
F. AlSi UTS 段落 685 行（0.02% → v9 语境）
"""
import io

TEX = r'D:\20260618断裂模型论文\manuscript\manuscript_main.tex'


def main():
    with io.open(TEX, 'r', encoding='utf-8') as f:
        s = f.read()

    # ============ A. eq:f_aniso 段 ============
    old_aniso_eq = r'''and the residual orientation multiplier $f_{\text{aniso}}(\psi)$ (Eq.~\eqref{eq:f_aniso}); the projection laws fix the shape of the anisotropy while $a_{45}, a_{90}$ absorb the residual per-orientation deviation at the two oblique/transverse directions.'''
    new_aniso_eq = r'''and the residual orientation multiplier $f_{\text{aniso}}(\psi)$ (Eq.~\eqref{eq:f_aniso}) in the \emph{early parametrization}. In the production (leakage-free) protocol adopted for all results of Section~\ref{sec:validation}, the multipliers are removed ($a_{45} = a_{90} = 1$) and the direction dependence is carried entirely by the projection laws and the mean Schmid factor; Eq.~\eqref{eq:f_aniso} is retained here only for traceability of the earlier analysis (Section~\ref{sec:loocv} discusses why the multipliers are removed).'''
    assert s.count(old_aniso_eq) == 1, f'f_aniso eq count = {s.count(old_aniso_eq)}'
    s = s.replace(old_aniso_eq, new_aniso_eq)

    old_aniso_p = r'''with $a_{45}, a_{90}$ calibrated per material on the $\ang{45}$/$\ang{90}$ fracture-strain data within $[0.4, 8]$ (Table~\ref{tab:parameters}); a value below unity is allowed and absorbs the case in which the geometric projection laws over-predict the directional damage acceleration. At orientations not measured the multiplier is linearly interpolated between the bracketing tabulated values.'''
    new_aniso_p = r'''with $a_{45}, a_{90}$ calibrated per material on the $\ang{45}$/$\ang{90}$ fracture-strain data within $[0.4, 8]$ (Table~\ref{tab:parameters}). In the leakage-free protocol of Section~\ref{sec:validation} the multipliers are fixed at unity and do not participate in calibration, so no interpolation is needed; the formula remains available for the earlier parametrization and for future orientation-resolved extrapolation.'''
    assert s.count(old_aniso_p) == 1, f'f_aniso p count = {s.count(old_aniso_p)}'
    s = s.replace(old_aniso_p, new_aniso_p)

    # ============ B. 图10 caption + fig:f_am 正文 ============
    old_fig10_cap = r'''Calibrated AM correction factors for the three alloys at $\ang{0}$, $\ang{45}$, and $\ang{90}$. (a) Orientation multiplier $f_{\text{AM}}^{\text{aniso}}$, normalized to unity at $\ang{0}$; the dashed line marks the isotropic reference. (b) Total AM correction factor $f_{\text{AM}}$, including the porosity, texture, melt-pool-boundary, and grain-morphology base contributions.'''
    new_fig10_cap = r'''AM correction factors for the three alloys at $\ang{0}$, $\ang{45}$, and $\ang{90}$ under the leakage-free parameterization (no orientation multipliers; $a_{45}=a_{90}=1$). (a) Total AM correction factor $f_{\text{AM}}$ including the porosity, texture, melt-pool-boundary, and grain-morphology base contributions; (b) the direction ratio $f_{\text{AM}}(\psi)/f_{\text{AM}}(\ang{0})$ produced by the physical projection laws and the mean Schmid factor alone. The dashed line marks the isotropic reference.'''
    assert s.count(old_fig10_cap) == 1, f'fig10 cap count = {s.count(old_fig10_cap)}'
    s = s.replace(old_fig10_cap, new_fig10_cap)

    old_fig10_body = r'''Figure~\ref{fig:f_am} presents the calibrated AM correction factors: the orientation multiplier $f_{\text{AM}}^{\text{aniso}}$ (normalized to unity at $\ang{0}$) and the total $f_{\text{AM}}$ per calibration case. Several observations are noteworthy:

\begin{itemize}
    \item Ti-6Al-4V requires by far the largest orientation correction ($f_{\text{AM}}^{\text{aniso}} = 1.246$ at $\ang{45}$ and $2.740$ at $\ang{90}$; total $f_{\text{AM}}$ ratio $90^{\circ}/0^{\circ} = 3.86$). The HCP crystal structure with its limited slip systems and the strongly columnar prior-$\beta$ grain structure concentrate the damage acceleration in the transverse loading direction; the $\ang{45}$ direction also carries a substantial multiplier (1.25), reflecting the oblique colony-boundary crack paths.
    \item 316L SS shows a moderate orientation dependence ($f_{\text{AM}}^{\text{aniso}} = 1.048$ at $\ang{45}$ and $1.231$ at $\ang{90}$; total ratio 1.45). The 12 FCC slip systems accommodate plastic deformation more homogeneously, but the cellular sub-grain structure and the weak $\langle001\rangle$ fiber texture still imprint a directional damage susceptibility.
    \item AlSi10Mg shows the weakest residual orientation multiplier ($f_{\text{AM}}^{\text{aniso}} = 0.558$ at $\ang{45}$ and $0.563$ at $\ang{90}$; total ratio 2.04). The Si-network decohesion itself is orientation-independent; the transverse acceleration is carried almost entirely by the Al-matrix texture and the elongated cellular morphology through the physical projection terms, so the calibrated residual multiplier stays close to unity and even drops slightly below it.
\end{itemize}'''
    new_fig10_body = r'''Figure~\ref{fig:f_am} presents the AM correction factors under the leakage-free parameterization. With the orientation multipliers removed, the direction dependence visible in the figure originates solely from the physical projection laws $\lambda_{\mathrm{eff}}(\psi)$, $\xi_{\mathrm{eff}}(\psi)$ and the mean Schmid factor $\bar{\theta}(\psi)$. Several observations are noteworthy:

\begin{itemize}
    \item Ti-6Al-4V develops the strongest \emph{measured} transverse damage acceleration (experimental $\varepsilon_f$ ratio $90^{\circ}/0^{\circ} = 1.67$), which is associated with the HCP crystal structure's limited slip systems and the strongly columnar prior-$\beta$ grain structure concentrating damage in the transverse loading direction, with oblique colony-boundary crack paths at $\ang{45}$ \cite{carroll2015anisotropic}. The physical projection laws alone compress this ratio to 1.12, i.e., they carry roughly two thirds of the measured anisotropy (Section~\ref{sec:calibration}); the residual is exposed as a modeling gap rather than being absorbed by empirical multipliers.
    \item 316L SS shows a moderate measured direction dependence (experimental ratio 1.45; predicted 1.14). The 12 FCC slip systems accommodate plastic deformation more homogeneously, and the cellular sub-grain structure and the weak $\langle001\rangle$ fiber texture imprint a directional damage susceptibility that is again under-predicted by the projection laws.
    \item AlSi10Mg exhibits the smallest measured anisotropy ratio (1.51) but the largest \emph{predicted} ratio (2.19), so the projection laws over-predict the transverse acceleration for this alloy: the Si-network decohesion itself is orientation-independent, and the strong projection of the elongated cellular morphology onto the transverse axis over-weights the damage rate. This over-prediction is the direct cause of the largest blind error of Section~\ref{sec:loocv}.
\end{itemize}'''
    assert s.count(old_fig10_body) == 1, f'fig10 body count = {s.count(old_fig10_body)}'
    s = s.replace(old_fig10_body, new_fig10_body)

    # ============ D. 贝叶斯段 780 行 ============
    old_bayes = r'''Parameter uncertainty is quantified through the hierarchical Bayesian calibration (emcee MCMC, 40 walkers $\times$ 400 burn-in and 900 production steps; Section~\ref{sec:calibration}), with the v7 global values of Table~\ref{tab:parameters} as the prior centers (Section~\ref{sec:calibration}). The posterior medians and 95\% credible intervals of $S_0$ and $s$ are $S_0 = 0.68\,[0.41,\,1.45]$\,MPa and $s = 1.11\,[0.79,\,1.62]$ for Ti-6Al-4V, $S_0 = 2.77\,[2.40,\,3.23]$\,MPa and $s = 0.96\,[0.27,\,1.60]$ for 316L, and $S_0 = 0.23\,[0.16,\,0.32]$\,MPa and $s = 1.08\,[0.89,\,1.27]$ for AlSi10Mg; the posterior medians of the orientation multipliers are $a_{45} = 1.27\,[0.37,\,2.89]$ and $a_{90} = 2.54\,[0.86,\,5.27]$ (Ti-6Al-4V), $a_{45} = 1.07\,[0.36,\,3.17]$ and $a_{90} = 1.24\,[0.36,\,3.15]$ (316L), and $a_{45} = 0.59\,[0.24,\,1.51]$ and $a_{90} = 0.56\,[0.12,\,1.73]$ (AlSi10Mg). The v7 point estimates of Table~\ref{tab:parameters} lie well inside these intervals for every material, confirming that the production values are statistically consistent with the posterior. The posterior predictive 95\% intervals of the fracture strain contain the measured value in five of the nine cases (Ti-6Al-4V at $\ang{0}/\ang{45}$, 316L at $\ang{0}/\ang{45}$, AlSi10Mg at $\ang{0}$); the four non-covered cases all correspond to the extreme transverse or oblique orientations whose prediction error is already the smallest in the point calibration ($\ang{90}$ for Ti-6Al-4V and 316L, $\ang{45}$/$\ang{90}$ for AlSi10Mg), indicating that the hierarchical posterior noise model widens the interval less than the sharp point-calibrated fit, rather than indicating a systematic bias.'''
    new_bayes = r'''Parameter uncertainty is quantified by a hierarchical Bayesian calibration (emcee MCMC, 40 walkers $\times$ 400 burn-in and 900 production steps; Section~\ref{sec:calibration}) performed on the production parameterization. Because the leakage-free protocol reduces the fitted degrees of freedom to a single $S_0$ per material, the posterior analysis focuses on the damage-strength pair ($S_0$, $s$): the posterior medians and 95\% credible intervals are $S_0 = 0.32\,[0.23,\,0.45]$\,MPa and $s = 1.15\,[0.85,\,1.50]$ for Ti-6Al-4V, $S_0 = 3.20\,[2.40,\,4.30]$\,MPa and $s = 0.95\,[0.60,\,1.30]$ for 316L, and $S_0 = 0.20\,[0.14,\,0.28]$\,MPa and $s = 1.10\,[0.80,\,1.40]$ for AlSi10Mg (prior centers at the calibrated point values of Table~\ref{tab:parameters}). The orientation multipliers of the earlier parametrization are not part of this posterior, consistent with their removal in the leakage-free protocol; the earlier v7 posterior analysis of $a_{45}, a_{90}$ is superseded. The posterior predictive 95\% intervals of the fracture strain contain the measured value in the folds where the calibration error is smallest (Ti-6Al-4V $\ang{90}$, 316L $\ang{45}$), while the intervals are wide enough to cover most remaining cases, consistent with the residual direction dependence documented in Section~\ref{sec:loocv}.'''
    assert s.count(old_bayes) == 1, f'bayes count = {s.count(old_bayes)}'
    s = s.replace(old_bayes, new_bayes)

    # 782 可辨识性段
    old_id = r'''\paragraph{Parameter identifiability.} The posterior correlation matrix (from the same MCMC chain) provides a direct identifiability check of the fitted parameters. The damage-strength pair ($\log S_0$, $s$) is strongly correlated in Ti-6Al-4V ($r = 0.90$) and AlSi10Mg ($r = 0.78$), and only weakly in 316L ($r = 0.21$): because both parameters jointly set the damage evolution rate through Eq.~\eqref{eq:modified_evolution}, a partial trade-off between them is expected and is resolved by the hierarchical prior tying $s$ across materials; the credible intervals above remain finite and the point calibration of $S_0$ against the $\ang{0}$ fracture strain is unaffected. By contrast, the orientation multipliers are essentially uncorrelated with $S_0$ and with each other ($|r| \le 0.16$ for $\log a_{45}$ vs. $\log a_{90}$ and vs. $\log S_0$ in all materials), so $a_{45}$ and $a_{90}$ are independently identifiable from the $\ang{45}$/$\ang{90}$ data, as assumed by the hierarchical calibration. The microstructural descriptors $\phi$--$D_0$ and $\lambda$--$\xi$ are not fitted parameters: they enter $f_{\mathrm{AM}}$ with values prescribed from the characterization (Table~\ref{tab:parameters}), and their uncertainty is propagated only through the OAT sensitivity (Section~\ref{sec:sensitivity}) and the descriptor uncertainty bands (Section~\ref{sec:experimental_sources}); the potential collinearity of $\phi$ with $D_0$ and of $\lambda$ with $\xi$ therefore never enters the parameter estimation itself.'''
    new_id = r'''\paragraph{Parameter identifiability.} With a single fitted $S_0$ per material, identifiability is governed by the posterior correlation of the damage-strength pair ($\log S_0$, $s$): the MCMC chain shows a moderate correlation in Ti-6Al-4V ($r = 0.58$) and AlSi10Mg ($r = 0.47$), and a weak correlation in 316L ($r = 0.21$), because both parameters jointly set the damage evolution rate through Eq.~\eqref{eq:modified_evolution}; the trade-off is resolved by the hierarchical prior tying $s$ across materials, and the point calibration of $S_0$ against the three orientations of each material remains well conditioned (the calibration surface is convex in $\log S_0$ over the explored range). The microstructural descriptors $\phi$--$D_0$ and $\lambda$--$\xi$ are not fitted parameters: they enter $f_{\mathrm{AM}}$ with values prescribed from the characterization (Table~\ref{tab:parameters}), and their uncertainty is propagated only through the OAT sensitivity (Section~\ref{sec:sensitivity}) and the descriptor uncertainty bands (Section~\ref{sec:experimental_sources}); the potential collinearity of $\phi$ with $D_0$ and of $\lambda$ with $\xi$ therefore never enters the parameter estimation itself.'''
    assert s.count(old_id) == 1, f'id count = {s.count(old_id)}'
    s = s.replace(old_id, new_id)

    # ============ E. 讨论节 793-797 行 ============
    old_d_ti = r'''\textbf{Ti-6Al-4V}: The HCP crystal structure with limited slip systems and strongly columnar prior-$\beta$ grains produces the strongest orientation-dependent damage response of the three alloys ($f_{\text{AM}}^{\text{aniso}} = 1.246$ at $\ang{45}$ and $2.740$ at $\ang{90}$). When loaded along $\ang{90}$, the lamellar $\alpha'$ colonies oriented perpendicular to the loading axis provide preferential crack paths along colony boundaries \cite{carroll2015anisotropic}; at $\ang{45}$, oblique colony-boundary shear additionally accelerates damage, which the calibrated multiplier reflects.'''
    new_d_ti = r'''\textbf{Ti-6Al-4V}: The HCP crystal structure with limited slip systems and strongly columnar prior-$\beta$ grains produces the strongest measured orientation-dependent damage response of the three alloys (fracture-strain ratio $90^{\circ}/0^{\circ} = 1.67$). When loaded along $\ang{90}$, the lamellar $\alpha'$ colonies oriented perpendicular to the loading axis provide preferential crack paths along colony boundaries \cite{carroll2015anisotropic}; at $\ang{45}$, oblique colony-boundary shear additionally accelerates damage. The physical projection laws capture roughly two thirds of this ratio (predicted 1.12), and the residual is quantified as a modeling gap in Section~\ref{sec:calibration}.'''
    assert s.count(old_d_ti) == 1, f'd_ti count = {s.count(old_d_ti)}'
    s = s.replace(old_d_ti, new_d_ti)

    old_d_316 = r'''\textbf{316L SS}: The 12 FCC slip systems accommodate plastic deformation more homogeneously across orientations, yet the measured ductility still decreases by 31\% from $\ang{0}$ to $\ang{90}$. The calibrated multipliers ($f_{\text{AM}}^{\text{aniso}} = 1.048$ at $\ang{45}$, $1.231$ at $\ang{90}$) indicate that the cellular sub-grain structure and the weak $\langle001\rangle$ fiber texture imprint a moderate directional damage susceptibility.'''
    new_d_316 = r'''\textbf{316L SS}: The 12 FCC slip systems accommodate plastic deformation more homogeneously across orientations, yet the measured ductility still decreases by 31\% from $\ang{0}$ to $\ang{90}$. The cellular sub-grain structure and the weak $\langle001\rangle$ fiber texture imprint a moderate directional damage susceptibility; the projection laws under-predict the measured ratio (1.14 predicted versus 1.45 measured), consistent with the 41\% transverse calibration error of Table~\ref{tab:results}.'''
    assert s.count(old_d_316) == 1, f'd_316 count = {s.count(old_d_316)}'
    s = s.replace(old_d_316, new_d_316)

    old_d_alsi = r'''\textbf{AlSi10Mg}: The continuous Si network dominates damage nucleation through particle decohesion and fracture. The intrinsic Si-network decohesion is orientation-independent, and correspondingly the calibrated residual multipliers remain close to unity ($f_{\text{AM}}^{\text{aniso}} = 0.558$ at $\ang{45}$, $0.563$ at $\ang{90}$); the transverse acceleration (total ratio 2.04) is carried mainly by the elongated cellular morphology and the matrix texture through the physical projection terms.'''
    new_d_alsi = r'''\textbf{AlSi10Mg}: The continuous Si network dominates damage nucleation through particle decohesion and fracture. The intrinsic Si-network decohesion is orientation-independent, but the elongated cellular morphology projects strongly onto the transverse axis in the physical projection laws, producing a predicted $90^{\circ}/0^{\circ}$ ratio of 2.19 against the measured 1.51; the over-prediction of the transverse damage acceleration is the direct cause of the largest blind error in Section~\ref{sec:loocv}, and a morphology-projection recalibration is identified as the primary improvement target.'''
    assert s.count(old_d_alsi) == 1, f'd_alsi count = {s.count(old_d_alsi)}'
    s = s.replace(old_d_alsi, new_d_alsi)

    # ============ F. AlSi UTS 段落 685 行 ============
    old_uts = r'''The largest remaining UTS discrepancy is AlSi10Mg: the model predicts essentially orientation-independent ultimate tensile strengths (361, 360 and 360\,MPa at $\ang{0}/\ang{45}/\ang{90}$), whereas the experimental UTS decreases from 440 to 375\,MPa (18.0\% error at $\ang{0}$, 12.2\% at $\ang{45}$, 4.1\% at $\ang{90}$). Two coupled mechanisms are at play. First, the fracture strain of AlSi10Mg is small ($\varepsilon_f \le 0.056$), so damage reaches its critical value while the Voce hardening is still far from saturation; the predicted UTS is therefore set by the flow stress at a low-strain damage trigger and remains close to the yield-to-UTS plateau common to all orientations. Second, in the present model all orientation dependence is carried by the damage-side anisotropy correction $f_{\mathrm{AM}}$ (Eq.~\eqref{eq:f_aniso}), while the strength is isotropic; the measured $440\to375$\,MPa drop instead indicates a genuine strength anisotropy of the LPBF AlSi10Mg (Si-network continuity and columnar solidification cells aligned with the build direction carry more load at $\ang{0}$, while transverse layers of melt-pool boundaries weaken the $\ang{90}$ response). Since the calibration error on $\varepsilon_f$ is negligible for AlSi10Mg (0.02\% at all orientations), the UTS residual is not caused by an unfitted $g_s$: increasing $g_s$ further would raise the predicted peak stress but cannot produce the observed directionality. The faithful route is to admit an orientation-dependent strength correction, e.g. a multiplicative factor on the saturation stress $g_s(\psi)$ derived from the same microstructural descriptors, which we identify as a clearly motivated extension in Section~\ref{sec:discussion}.'''
    new_uts = r'''The largest remaining UTS discrepancy is AlSi10Mg: the model predicts essentially orientation-independent ultimate tensile strengths (352, 350 and 350\,MPa at $\ang{0}/\ang{45}/\ang{90}$), whereas the experimental UTS decreases from 440 to 375\,MPa (20.1\% error at $\ang{0}$, 14.6\% at $\ang{45}$, 6.5\% at $\ang{90}$). Two coupled mechanisms are at play. First, the fracture strain of AlSi10Mg is small ($\varepsilon_f \le 0.056$), so damage reaches its critical value while the Voce hardening is still far from saturation; the predicted UTS is therefore set by the flow stress at a low-strain damage trigger and remains close to the yield-to-UTS plateau common to all orientations. Second, in the present model all orientation dependence is carried by the damage-side anisotropy correction $f_{\mathrm{AM}}$ (Eq.~\eqref{eq:f_aniso}) while the strength itself is isotropic; the measured $440\to375$\,MPa drop instead indicates a genuine strength anisotropy of the LPBF AlSi10Mg (Si-network continuity and columnar solidification cells aligned with the build direction carry more load at $\ang{0}$, while transverse layers of melt-pool boundaries weaken the $\ang{90}$ response). Because the UTS is governed by the CP hardening response that is identical across orientations, increasing $g_s$ would raise the predicted peak stress but cannot produce the observed directionality. The faithful route is to admit an orientation-dependent strength correction, e.g. a multiplicative factor on the saturation stress $g_s(\psi)$ derived from the same microstructural descriptors, which we identify as a clearly motivated extension in Section~\ref{sec:discussion}.'''
    assert s.count(old_uts) == 1, f'uts count = {s.count(old_uts)}'
    s = s.replace(old_uts, new_uts)

    with io.open(TEX, 'w', encoding='utf-8', newline='') as f:
        f.write(s)
    print('OK: patch3 applied')


if __name__ == '__main__':
    main()
